### ISSUE TITLE
Forwarding of email leads to error page

### ISSUE THREAD

**Issue by devondragon** [devondragon/10MinuteMailPublic#1]
From an email I received:

>  I have one issue with 10minutemail, more precisely with forwarding e-mail functionality. In my case it doesn't work. When I see new e-mail in 10minutemail.com in my temporary inbox, I choose option to forward it, give my actual e-mail (the one I'm writing from XXXXXXXXX) and hit the „Forward” button. I get no message that my e-mail has been forwarded but instead „Your e-mail address has self-destructed” is shown, I have no option to go back to my tmp-inbox (e-mail hasn't expired) and get no e-mail in my actual inbox :(

**Comment by devondragon** [comment]
FWIW I tested this myself and it worked as expected.  No errors and I received the forwarded email to my gmail account.

**Comment by devondragon** [comment]
I believe the error is due to this:

`Caused by: java.lang.NullPointerException
        at com.sun.mail.handlers.text_plain.writeTo(text_plain.java:121)
        at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:869)
        at javax.activation.DataHandler.writeTo(DataHandler.java:302)
        at javax.mail.internet.MimeUtility.getEncoding(MimeUtility.java:248)
        at javax.mail.internet.MimeBodyPart.updateHeaders(MimeBodyPart.java:1268)
        at javax.mail.internet.MimeBodyPart.updateHeaders(MimeBodyPart.java:1001)
        at javax.mail.internet.MimeMultipart.updateHeaders(MimeMultipart.java:333)
        at javax.mail.internet.MimeBodyPart.updateHeaders(MimeBodyPart.java:1255)
        at javax.mail.internet.MimeMessage.updateHeaders(MimeMessage.java:2012)
        at javax.mail.internet.MimeMessage.saveChanges(MimeMessage.java:1980)
        at com.digitalsanctuary.mail.SMTPClient.sendMail(SMTPClient.java:143)`

**Comment by dkrysiak** [comment]
Hi,

It turns out that the bug doesn't occur always. I've tried again few times and reproduced the error only on one kind of e-mail, e-mail having almost only one big html table. I'll try to sent example of this e-mail to your personal address later.

Thanks again
Dawid

**Comment by devondragon** [comment]
I think it may be a bug in the old JavaMail 1.4.0 that's in place.  I just tried an upgrade but that broke things so rolled back.  Sorry for the disruption everyone!

Yeah if you can send me a sample or attach one here in a zip, that would be great.  I'm working on a whole new version of 10MinuteMail now, so I want to be sure I test edge cases like that.  Thanks!

**Comment by devondragon** [comment]
Unfortunately seeing a similar thing in the new Beta version of 10MinuteMail:

`caused by java.lang.NullPointerException
               com.sun.mail.handlers.text_plain.writeTo (text_plain.java:129)

      javax.activation.ObjectDataContentHandler.writeTo (DataHandler.java:897)

                   javax.activation.DataHandler.writeTo (DataHandler.java:330)

            javax.mail.internet.MimeUtility.getEncoding (MimeUtility.java:324)

         javax.mail.internet.MimeBodyPart.updateHeaders (MimeBodyPart.java:1525)

         javax.mail.internet.MimeBodyPart.updateHeaders (MimeBodyPart.java:1131)

        javax.mail.internet.MimeMultipart.updateHeaders (MimeMultipart.java:515)

         javax.mail.internet.MimeBodyPart.updateHeaders (MimeBodyPart.java:1483)

          javax.mail.internet.MimeMessage.updateHeaders (MimeMessage.java:2198)
javax.mail.internet.MimeMessage.updateHeaders

            javax.mail.internet.MimeMessage.saveChanges (MimeMessage.java:2159)

          com.tenminutemail.clients.SMTPClient.sendMail (SMTPClient.java:140)
com.tenminutemail.clients.SMTPClient.sendMail

….clients.SMTPClient$Proxy$_$$_WeldClientProxy.sendMail (Unknown Source)

      com.tenminutemail.session.UserSession.sendForward (UserSession.java:255)

…sion.UserSession$Proxy$_$$_WeldClientProxy.sendForward (Unknown Source)
com.tenminutemail.session.UserSession$Proxy$_$$_WeldClientProxy.sendForward

       com.tenminutemail.api.MessagesAPI.forwardMessage (MessagesAPI.java:81)

…i.MessagesAPI$Proxy$_$$_WeldClientProxy.forwardMessage (Unknown Source)`

**Comment by devondragon** [comment]
I'm committing a potential fix now and will push to Beta shortly.

**Comment by devondragon** [comment]
Change pushed to https://beta.10minutemail.com  

Will be monitoring for more instances off this error.

**Comment by devondragon** [comment]
@dkrysiak can you retest this using https://beta.10minutemail.com and let me know if the issue still happens?

**Comment by devondragon** [comment]
I haven't seen any further occurrences of this issue in the past two weeks, so I am going to close this down.

**Comment by dkrysiak** [comment]
Problem still occurs on main 10minutemail.com
Problem doesn't occur on beta – I've forwarded e-mail successfully.

**Comment by devondragon** [comment]
Great!  Beta will be going live as the main 10Minutemail in the next couple of weeks.

**Comment by anidotnet** [comment]
May I ask how did you solved the NPE in javamail when content type is text/plain. I am also getting the same in my program. I just wanted to know the way you have solved it (if you don't have any obligation).

Thanks..

**Comment by devondragon** [comment]
Sure thing!

My old code was this:

```java
MimeMultipart multipart = new MimeMultipart(ALTERNATIVE);
MimeBodyPart tp = new MimeBodyPart();		 
tp.setText(pTextBody, UTF_8);
multipart.addBodyPart(tp);
```

I replaced the 3rd line with an if/else like this:

```java
MimeMultipart multipart = new MimeMultipart(ALTERNATIVE);
MimeBodyPart tp = new MimeBodyPart();		 
if (pTextBody == null) {
   tp.setText("", UTF_8);
} else {
   tp.setText(pTextBody, UTF_8);
}
multipart.addBodyPart(tp);
```

**Comment by anidotnet** [comment]
Thanks a lot!! Cheers..
