### ISSUE TITLE
HTML tags don't work in About/FAQ

### ISSUE THREAD

**Issue by TicClickie** [devondragon/10MinuteMailPublic#13]
https://10minutemail.com/10MinuteMail/faq.html?dswid=-1677, at "Why would I use 10MinuteMail?"
When translating, I also relied on the use of tags in a place, or two, or three, so..

**Comment by devondragon** [comment]
Switching from simple JSF EL to using the JSF HTML outputText tag with the escape="false" attribute to allow for HTML tags in the messages.

**Comment by devondragon** [comment]
Changes pushed in Beta, the EN stuff looks good.  Pushing to PRD now.
