### ISSUE TITLE
Old design vs New Design

### ISSUE THREAD

**Issue by 2br-2b** [devondragon/10MinuteMailPublic#15]
Hello!

Is there any way to say whether we like the old design or the new design better?

Personally, I kind of prefer the old design. It's small, simple, and to the point. Of course, I'm sure you're putting tons of work into this service (which is amazing, by the way), and I'm sure that it'll be much easier for you with the new design.

**Comment by devondragon** [comment]
Huh!  Interesting!  I worried that the old design felt.. old.  dated.   too small.  etc..  

The new design is part of a completely new backend as well, so the ship may have sailed, but I'm going to think about this now.  I honestly hadn't expected anyone to like the old design better:). 

Is there anything that could be changed on the new design that would make it better for you?

**Comment by 2br-2b** [comment]
I like the simplicity of the original design better. I like how it has icons, which are quicker and easier to recognize and understand than reading the buttons on the new design. I also like how much more compact it is than the new design.

I do agree that it does look a little dated, but it's not really that bad.

If, on the other hand, the new design comes with a new back end, as a fellow programmer, I would encourage you to go for it!

**Comment by devondragon** [comment]
Thanks for the feedback.  I am definitely not a designer myself.  I can't promise anything but I will keep your feedback in mind for future evolutions of the design.  I hope you'll stick with us on the new site though!!

**Comment by 2br-2b** [comment]
I definitely will!  I just discovered the site, and I love it!  I've never found anything like it, and I'm definitely going to use it!
