### ISSUE TITLE
Time remaining counter is breaking

### ISSUE THREAD

**Issue by adgonzalez-ml** [devondragon/10MinuteMailPublic#16]
When u click multiple times in a small span of time the 10 more minutes button the counter breaks. It seems it starts a new function that handles the cooldown instead of just setting the time remaining to 10 minutes again.

Dont know hoy to put the video in a gif. So heres a link https://drive.google.com/file/d/1h4ozxeTxop-3o68y7-qj7W2xMXNlR9h7/view?usp=sharing

**Comment by devondragon** [comment]
Thanks!  I was able to reproduce the issue.  Will check with my front end dev.
