### ISSUE TITLE
Timer background repeats (is ugly) on larger than 1080p screens

### ISSUE THREAD

**Issue by Niksuski** [devondragon/10MinuteMailPublic#18]
I fixed it in-browser by adding the highlighted changes:

10minutemail.css:1
#main_content {
    background: url(/img/10minutemail_main_bg.jpg) **no-repeat**;
        background-size: **cover**;
    color: #fff;
    height: 500px;

**Comment by devondragon** [comment]
Awesome!!  Thank you!  I will work on this fix.

**Comment by devondragon** [comment]
Fixed and pushed to PRD
