### ISSUE TITLE
10 Minute Email - Inbox problem

### ISSUE THREAD

**Issue by KMacInHS** [devondragon/10MinuteMailPublic#21]
Regarding temp email address: ruteiukxvxcnggbngv@kiabws.com. Used this email for a signup on website.
I am using Safari for Mac 13.1.2. Does not seem to be a live link to Inbox on the 10 Minute Email page. No response when I move my mouse over it. I've been adding time for the last hour or so. No change to "Inbox 0".
Karen
<img width="1057" alt="Screen Shot 2021-01-24 at 12 13 14 PM" src="https://user-images.githubusercontent.com/77931922/105637849-99b93580-5e3d-11eb-9f96-c1b2f8024ace.png">

**Comment by devondragon** [comment]
@KMacInHS Thanks for reporting this.  I just tested using Safari 14.0.2 and everything seems to be working fine (counter is counting down, emails are arriving and displaying properly, etc...

Can you try restarting the browser and seeing if 10MinuteMail is still broken for you?

**Comment by KMacInHS** [comment]
Hi Devon,
Thanks for your quick reply. I just sent a test email to the temp address to test it, and it worked, so apparently the website I am waiting on has not responded. Sorry to bother you. I see how it works now.
Thanks, Karen

**Comment by devondragon** [comment]
No problem!  Glad I could help!
