### ISSUE TITLE
Enhancement request: customized email address

### ISSUE THREAD

**Issue by glh290** [devondragon/10MinuteMailPublic#9]
It would be nice to be able to edit the email address from "XXXXXXXX@trbvm.com" to something between 1-10 characters like "69tested8@trbvm.com" so in the case that a email does self destruct and the user didn't get the email they where waiting for (or maybe closed out of the browser as i had a few times) they could easily edit it and get back to receiving the email they wanted to get. guerrill amail has this, but there were a couple things i used 10 minutemail for that i wanted to switch to my legit email but of coarse cant with the current setup of 10minutemail, (keep that "give me 10 more minutes" button i slap that like a snooze alarm xD)

**Comment by devondragon** [comment]
The issues that I see with allowing users to set an email address, and worse, enter that address in later and get access to the inbox, are:

1. Security.  Anyone who knows or guesses an address you used, will have access to your emails, and can issue a forgot password flow and take over an account you registered.  So you'd need to do something like provide a secure password as well, and now you're basically signing up for an email account with me, and I'm having to do a ton of new features/data/support.  

2. Persistence.  Right now, the inbox is ephemeral.  The address expires and the inbox goes away.  Emails aren't saved, and future emails are denied.  To provide the ability to come back to the site, and enter in an arbitrary address, I think many people would expect that address to have remained "active" and to have access to an inbox with all the email sent to that address in the intervening time.  This adds the need for persistent storage, something that I have avoided thus far (for simplicity and security).  How long should that last for?  

I'm happy to discuss further here, I don't want to dismiss any user requested feature out of hand, but inbox security is very important to me, so I want to be sure there's a solid solution available, and that increased complexity is offset by real value.  

Thanks!

**Comment by devondragon** [comment]
Closing as won't-fix due to lack of feedback/solutions around concerns.
